name: Shop
author: Tanner Embry (SnowGears)
description: Easily create shops to buy or sell items!
version: 1.4.7
main: com.snowgears.shop.Shop
softdepend: [Vault]
permissions:
    shop.use:
        description: Allows player to use shops.
        default: op
    shop.create:
        description: Allows player to create shops.
        default: op
    shop.destroy:
        description: Allows player to destroy their own shops.
        default: op
    shop.operator:
        description: Allows access to operator actions.
        default: op
commands:
   shop:
      description: Different commands pertaining to plugin
      usage: /<command>